
name: iOS CI/CD

on:
  push:
    branches:
      - marsh_v1

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Xcode
      uses: actions/setup-xcode@14.3.1
      with:
        xcode-version: '14.3.1' # Adjust version as needed

    - name: Install Dependencies
      run: |
        bundle install
        bundle exec fastlane setup

    - name: Build and Test
      run: |
        bundle exec fastlane build_and_test

    - name: Deploy to TestFlight
      if: success()
      run: |
        bundle exec fastlane deploy_to_testflight
